import { lazyWithRetry } from '../utils/lazyWithRetry';

/** Rutas pesadas en chunks separados (code-splitting). Auth públicas siguen en index (carga inmediata). */
export const Dashboard = lazyWithRetry(() => import('../pages/Dashboard'));
export const PacientesList = lazyWithRetry(() => import('../pages/pacientes/PacientesList'));
export const PacienteDetail = lazyWithRetry(() => import('../pages/pacientes/PacienteDetail'));
export const AgregarPaciente = lazyWithRetry(() => import('../pages/pacientes/AgregarPaciente'));
export const EditarPaciente = lazyWithRetry(() => import('../pages/pacientes/EditarPaciente'));
export const AgendarCita = lazyWithRetry(() => import('../pages/pacientes/AgendarCita'));
export const CitasList = lazyWithRetry(() => import('../pages/citas/CitasList'));
export const CitaDetail = lazyWithRetry(() => import('../pages/citas/CitaDetail'));
export const ReportesPage = lazyWithRetry(() => import('../pages/reportes/ReportesPage'));
export const DoctoresList = lazyWithRetry(() => import('../pages/doctores/DoctoresList'));
export const DoctorDetail = lazyWithRetry(() => import('../pages/doctores/DoctorDetail'));
export const AgregarDoctor = lazyWithRetry(() => import('../pages/doctores/AgregarDoctor'));
export const EditarDoctor = lazyWithRetry(() => import('../pages/doctores/EditarDoctor'));
export const AuditoriaList = lazyWithRetry(() => import('../pages/auditoria/AuditoriaList'));
export const AuditoriaDetail = lazyWithRetry(() => import('../pages/auditoria/AuditoriaDetail'));
export const CatalogosPage = lazyWithRetry(() => import('../pages/admin/CatalogosPage'));
export const UsuariosList = lazyWithRetry(() => import('../pages/admin/UsuariosList'));
export const AdminOperacionesPage = lazyWithRetry(() => import('../pages/admin/AdminOperacionesPage'));
export const AdminTicketsPage = lazyWithRetry(() => import('../pages/admin/AdminTicketsPage'));
export const NotificacionesDoctor = lazyWithRetry(() => import('../pages/doctor/NotificacionesDoctor'));
export const DoctorTicketsPage = lazyWithRetry(() => import('../pages/doctor/DoctorTicketsPage'));
export const TicketNuevoPage = lazyWithRetry(() => import('../pages/soporte/TicketNuevoPage'));
export const TicketDetailPage = lazyWithRetry(() => import('../pages/soporte/TicketDetailPage'));
export const SolicitudesReprogramacion = lazyWithRetry(() => import('../pages/doctor/SolicitudesReprogramacion'));
export const ChatList = lazyWithRetry(() => import('../pages/doctor/ChatList'));
export const ChatConversacion = lazyWithRetry(() => import('../pages/doctor/ChatConversacion'));
export const Perfil = lazyWithRetry(() => import('../pages/Perfil'));
