/**
 * Paleta IMSS Bienestar - misma que ClinicaMovil
 * Uso: import { COLORES } from '@/theme/colors';
 */
export const COLORES = {
  PRIMARIO: '#006657',
  PRIMARIO_LIGHT: '#0A7D6B',
  PRIMARIO_DARK: '#10312B',
  SECUNDARIO: '#BC955C',
  SECUNDARIO_LIGHT: '#DDC9A3',
  SECUNDARIO_DARK: '#9B7B4A',
  FONDO: '#F5F2ED',
  FONDO_SECUNDARIO: '#FAF8F5',
  FONDO_CARD: '#FFFFFF',
  TEXTO_PRIMARIO: '#212121',
  TEXTO_SECUNDARIO: '#5C5346',
  TEXTO_DISABLED: '#BDBDBD',
  TEXTO_EN_PRIMARIO: '#FFFFFF',
  EXITO: '#006657',
  ADVERTENCIA: '#BC955C',
  ERROR: '#9F2241',
  ERROR_LIGHT: '#B52D4D',
  BORDE_CLARO: '#DDC9A3',
  FONDO_VERDE_SUAVE: '#E8F0EE',
  FONDO_ERROR_CLARO: '#FDF2F4',
  BORDE_ERROR_CLARO: '#9F2241',
  NAV_PRIMARIO: '#006657',
  BLANCO: '#FFFFFF',
  NEGRO: '#000000',
};

export default COLORES;
